### ISSUE TITLE
Add Function to use our ArcGIS server services

### ISSUE THREAD

**Issue by RoboDonut** [Esri/Viewer#16]
Yeah... I know... Probably been asked 1,000 time already but i'm gonna ask again. 

First i'll say i am a total noob to javaScript, so please bear with me. 

Is there anyway we can get a function or methodology to use our own hosted services in this template?

the folks [here](https://geonet.esri.com/message/41574?sr=search&searchId=38321017-1504-4b21-b94f-0c82daedc2b4&searchIndex=0) have a decent function that worked in the old viewer but i am having great issue getting it to work here. I took there code and and put it into an file called buildWebMap.js in the js folder of the source but i am unable to get to reference it in the defaults.js file

Please help. 

```
   function createWebMap(){
        var webmap = {};
        webmap.item = {
        "title":"Local Data Layer",
        "snippet": "Local service",
        "extent": [[-139.4916, 10.7191],[-52.392, 59.5199]]
        };

        webmap.itemData = {
        "operationalLayers": [{
        "url": "http://<INTERNAL IP>/arcgis/rest/services/<SERVICE NAME>/MapServer",
        "visibility": true,
        "opacity": 0.75,
        "title": "Farms"
        }],
        "baseMap": {
        "baseMapLayers": [{
        "opacity": 1,
        "visibility": true,
        "url": "http://services.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer"
        },{
        "isReference": true,
        "opacity": 1,
        "visibility": true,
        "url": "http://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Reference_Overlay/MapServer"
        }],
        "title": "World_Terrain_Base"
        },
        "version": "1.1"
        };

        return webmap;
        }
```

**Comment by ezequias** [comment]
@jgravois talking about your comment for using ArcGIS Server via Portal there is any consumption of credits if I install my portal and than set my ArcGIS Service to it in the same custom environment?

I meant: It is need to make the client buy more credits or be vinculated to any anual singing to Esri even after buying the entire ArcGIS Server Enterprise platform?

**Comment by jgravois** [comment]
@ezequias i'm not positive i understand your question, but no credits are consumed when saving or reading webmaps.
