### ISSUE TITLE
base map gallery

### ISSUE THREAD

**Issue by ebonan** [Esri/Viewer#20]
First of all: very nice work!
 we downloaded the app and tried to configure the basemap gallery,  setting our basemaps group  but only the arcgis basemaps compare..

We tried to set parameters in the main.js
 in particular the function 
"_addBasemapGallery"var basemap = new BasemapGallery({  
                    id: "....", ..(we tried with our group name or our group ID)

and in the function
"_getBasemapGroup"

```
            basemapGroup = {
                "owner": "XXXXl", 
                "title": "Arpa Piemonte Geoportal Basemap",
                "id": "36d72c18fcf04e96bab3b73ef0e09a13"
            };
```

but nothing change. Any help is appreciated.
thank you 
Enrico

**Comment by wrayda** [comment]
I downloaded the App today, and I cannot get my organizations' basemap gallery to load in the app.  you can view the app at http://gisweb.roanokecountyva.gov/viewer/

Any ideas?

Thank you,
David

**Comment by jgravois** [comment]
@wrayda sorry for the delayed response.  i see both 2013 and 2011 aerial imagery display in your application so im under the impression that you were able to resolve the problem.  if not, let me know.
