### ISSUE TITLE
Edit session issue on Opera or Chrome using iOS with iPhone and iPad.

### ISSUE THREAD

**Issue by GeoGeeks** [Esri/Viewer#25]
When the edit map is activated and the application is running in the Google Chrome or Opera browser  on  Iphone and clicked on the "Editor" component restarts making it impossible to be able to add a new point.

![image](https://cloud.githubusercontent.com/assets/8257841/4725094/906d82b2-5956-11e4-865d-08126bce6782.png)

In the picture you can see how to select the option of adding point, just let selected appear but the menu never disappears, making it impossible to add the point and edit the layer

**Comment by kellyhutchins** [comment]
Is this the same issue as https://github.com/Esri/Viewer/issues/26? 

If not can you explain how they are different?
