### ISSUE TITLE
Edit on iPhone 5 or 5S or size of the screen similar

### ISSUE THREAD

**Issue by GeoGeeks** [Esri/Viewer#26]
In the mobile version of the basic display is difficult to create a new point on the map as to select the type of item, the popup window does not close and can not locate the point on the map.

When you use an Iphone 5 and 5s error is more evident as the size of the screen is smaller, when devices like Samsung s5 are used, it is possible to do the editing, but it would better if  this window once you selected point to report,  this window will disappear.

![img_9252](https://cloud.githubusercontent.com/assets/8257841/4725343/b85866f0-5958-11e4-86ec-ed8baa5283f5.PNG)

**Comment by kellyhutchins** [comment]
@GeoGeeks  I'll look at fixing this for a future release. If you are working with a locally hosted copy I can send you details on how to fix it in your app.
