### ISSUE TITLE
The title on the mobile version disappears

### ISSUE THREAD

**Issue by ghost** [Esri/Viewer#27]
The title on the mobile version disappears

![image](https://cloud.githubusercontent.com/assets/8257841/4725420/547bfc18-5959-11e4-9c45-b546a19b1a0f.png)

![image](https://cloud.githubusercontent.com/assets/8257841/4725428/6f10cd7e-5959-11e4-9c46-b03df2c13cb7.png)

**Comment by GeoGeeks** [comment]
Thanks!
