### ISSUE TITLE
Scrollbar inside edit session.

### ISSUE THREAD

**Issue by ghost** [Esri/Viewer#28]
When the edit window is created does not occupy the entire space of the component, which makes it difficult to Navigation

![image](https://cloud.githubusercontent.com/assets/8257841/4725528/41b9bdda-595a-11e4-88ff-4e965ae4235a.png)

![image](https://cloud.githubusercontent.com/assets/8257841/4725530/4d0b9e74-595a-11e4-92ec-938fc5758a67.png)

**Comment by GeoGeeks** [comment]
Thanks a lot!
