### ISSUE TITLE
bad link in README

### ISSUE THREAD

**Issue by jgravois** [Esri/Viewer#37]
"For addtional customization options view the [wiki](https://github.com/Esri/basic-viewer-template/wiki)"

right now this is pointing at the repo for the legacy viewer.  we should create an equivalent wiki for this repo and move @jsomerville's article there.

**Comment by kellyhutchins** [comment]
Created new wiki and moved @jsomerville's read-me info there. @jgravois  feel free to create an article for the custom url params
