### ISSUE TITLE
Sublayers Not Showing In Layers Widget

### ISSUE THREAD

**Issue by comfox** [Esri/Viewer#38]
When viewing the Layers widget where you can toggle map layers on and off, map services can't be expanded to show their sublayers and thus those sublayers can't individually be turned on and off.
![map_layers_example](https://cloud.githubusercontent.com/assets/10562704/5778964/0a1063a0-9d6d-11e4-9ed2-772cc7af5a44.jpg)

**Comment by kellyhutchins** [comment]
This is a known issue for now. In the future we plan to add support for sub-layers but we don't yet have a target date for when that capability will be added.
