### ISSUE TITLE
I'm missing something, how to define a different basemap, or rest server?

### ISSUE THREAD

**Issue by tggagne** [Esri/Viewer#41]
Maybe I misunderstood what the viewer was supposed to do for me.  I'm looking for a viewer I can use that will allow me to specify an alternative arcgis server and basemap.  It would be especially cool if it would find the layers on the rest server as well.

A bonus feature would be an input line to enter a location that could be geocoded by a default geocoder or an alternate one.

**Comment by kellyhutchins** [comment]
@tggagne  this is an application that allows you to view web maps from ArcGIS Online. It does provide the ability to choose an alternate base map for your map using the base map gallery tool but does not allow you to browse for additional services. The app also allows you to enter a location and it will use the Search widget to geocode that location. 

You may want to check out the ArcGIS Online Map Viewer capabilities because that sounds like it can do more of what you are looking for.

**Comment by tggagne** [comment]
Hmm.  Something must be missing then.  I'm not seeing the base map gallery tool or a field to enter a location.  Something must be configured oddly.

Regardless, I'll check-out the ArcGIS Online Map Viewer.  Hopefully, it's customizable.  I'll eventually need to replace the geocoder.

![screen shot 2015-03-04 at 9 06 17 pm](https://cloud.githubusercontent.com/assets/886672/6497796/67f1e0b0-c2b2-11e4-8cfe-0a9d05147fa6.png)

**Comment by kellyhutchins** [comment]
The online map viewer is not customizable.  So it looks like you have downloaded the code and are hosting it on your own web server. The tools should display so I think there's probably an error of some sort happening. Which browser are you using? Also if you open the developer tools for your browser are there any error messages in the dev console?

**Comment by tggagne** [comment]
I did download the code and have loaded into a Salesforce page.  Because Salesforce is a secure connection, it complains first about the mixed content.

After that it complains about some timeouts, then the inability to read layerInfos.

It's not perfect yet (obviously), but I'm hoping this is the right place to start.

The XMLHttpRequest progress event property 'position' is deprecated. Please use 'loaded' instead.
js.arcgis.com/3.13/init.js:162 Mixed Content: The page at 'https://esriviewer-dev-ed--c.na16.visual.force.com/apex/esriviewer' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tmservices1.esri.com/arcgis/rest/info?f=json'. This request has been blocked; the content must be served over HTTPS.

js.arcgis.com/3.13/init.js:1086 Mixed Content: The page at 'https://esriviewer-dev-ed--c.na16.visual.force.com/apex/esriviewer' was loaded over HTTPS, but requested an insecure script 'http://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/Weather_Warnings…apServer?f=json&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback'. This request has been blocked; the content must be served over HTTPS.

init.js:1484 dojo.io.script error q {message: "Timeout exceeded", response: Object, log: undefined, stack: (...), dojoType: "timeout"…}
init.js:1484 dojo.io.script error q {message: "Timeout exceeded", response: Object, log: undefined, stack: (...), dojoType: "timeout"…}
init.js:1484 dojo.io.script error q {message: "Timeout exceeded", response: Object, log: undefined, stack: (...), dojoType: "timeout"…}
init.js:1484 dojo.io.script error q {message: "Timeout exceeded", response: Object, log: undefined, stack: (...), dojoType: "timeout"…}
main.js:931 Uncaught TypeError: Cannot read property 'layerInfos' of undefined
Resource interpreted as Image but transferred with MIME type text/html: "https://esriviewer-dev-ed--c.na16.visual.force.com/apex/images/icons_white/layers.png".
Resource interpreted as Image but transferred with MIME type text/html: "https://esriviewer-dev-ed--c.na16.visual.force.com/apex/images/icons_white/bookmarks.png".
init.js:209 TypeError: Cannot read property 'on' of undefined {stack: (...), message: "Cannot read property 'on' of undefined"} "TypeError: Cannot read property 'on' of undefined
    at k (https://js.arcgis.com/3.13/init.js:217:506)
    at declare._layerEvent (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/TableOfContents.js:223:29)
    at declare._setLayerEvents (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/TableOfContents.js:289:30)
    at declare._createList (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/TableOfContents.js:189:22)
    at declare._init (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/TableOfContents.js:352:18)
    at declare.startup (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/TableOfContents.js:59:22)
    at declare._addLayers (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/main.js:406:25)
    at null.<anonymous> (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/main.js:130:44)
    at g.hitch (https://js.arcgis.com/3.13/init.js:177:296)
    at k (https://js.arcgis.com/3.13/init.js:199:431)
    ----------------------------------------
    rejected at a (https://js.arcgis.com/3.13/init.js:200:337)
    at k (https://js.arcgis.com/3.13/init.js:200:89)
    at f.then.b.then [as then] (https://js.arcgis.com/3.13/init.js:202:308)
    at declare._createUI (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/main.js:115:31)
    at declare._createMapUI (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/main.js:984:18)
    at null.<anonymous> (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/main.js:1107:22)
    at g.hitch (https://js.arcgis.com/3.13/init.js:177:296)
    at c (https://js.arcgis.com/3.13/init.js:76:221)
    at d (https://js.arcgis.com/3.13/init.js:76:10)
    at b.Deferred.resolve.callback (https://js.arcgis.com/3.13/init.js:77:350)
    ----------------------------------------
Error
    at f.then.b.then [as then] (https://js.arcgis.com/3.13/init.js:202:253)
    at declare._createUI (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/main.js:115:31)
    at declare._createMapUI (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/main.js:984:18)
    at null.<anonymous> (https://esriviewer-dev-ed--c.na16.visual.force.com/resource/1425509632000/esriviewer/js/main.js:1107:22)
    at g.hitch (https://js.arcgis.com/3.13/init.js:177:296)
    at c (https://js.arcgis.com/3.13/init.js:76:221)
    at d (https://js.arcgis.com/3.13/init.js:76:10)
    at b.Deferred.resolve.callback (https://js.arcgis.com/3.13/init.js:77:350)
    at ia (https://js.arcgis.com/3.13/init.js:505:92)
    at Pa (https://js.arcgis.com/3.13/init.js:507:60)"

**Comment by kellyhutchins** [comment]
I'm not familiar with loading an app into Salesforce but I think the first thing to try is to create a simple test map with just a standard ArcGIS Online basemap and use that as a test. The online basemaps are all available over https so that would get rid of the mixed content errors and let us see if that is the only issue or if something else is going on.

**Comment by tggagne** [comment]
We created our own application using the Javascript API, but that 
application requires maintenance.  I thought we'd try again using 
something from the public domain, and if we got it working, return it to 
the PD.

Essentially, importing it is straightforward even if getting it to work 
is not.  For anyone interested in the particulars on getting it to work 
inside SF I'm willing to collaborate.

The mixed content is a bummer because it looks like it's being called 
from within an arcgis library--and so isn't using the same 
protocol-independent syntax as the rest of the code.  Frankly, I'm 
unsure how easy it is to get such a thing corrected inside ESRI. I've 
not created a ticket against the API before.

**Comment by jgravois** [comment]
we provide robust technical support for our APIs as well as our COTS software.  I know because both @kellyhutchins and myself were on that end of the phone for years :smile:

in general, templates like the Viewer can be configured to run over HTTPs successfully, so a *simplified* reproducible test case would still be valuable for your own testing, or to provide our traditional technical support channel.

1. get the application running on your own web server (over HTTP) independent of Salesforce
2. get the application running over HTTPs
3. try to integrate with Salesforce

**Comment by tggagne** [comment]
I like those steps.  Will try it on a local server first.

**Comment by tggagne** [comment]
Ok.  I've reconfigured my local apache to support SSL connections, and 
am getting the same result.

Mixed Content: The page at 'https://localhost/Viewer/' was loaded over 
HTTPS, but requested an insecure XMLHttpRequest endpoint 
'http://tmservices1.esri.com/arcgis/rest/info?f=json'. This request has 
been blocked; the content must be served over HTTPS.
js.arcgis.com/3.13/init.js:1086 Mixed Content: The page at 
'https://localhost/Viewer/' was loaded over HTTPS, but requested an 
insecure script 
'http://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/Weather_Warnings…apServer?f=json&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback'. 
This request has been blocked; the content must be served over HTTPS.
js.arcgis.com/3.13/init.js:1086 Mixed Content: The page at 
'https://localhost/Viewer/' was loaded over HTTPS, but requested an 
insecure script 
'http://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/NOAA_METAR_curre…apServer?f=json&callback=dojo.io.script.jsonp_dojoIoScript2._jsonpCallback'. 
This request has been blocked; the content must be served over HTTPS.
js.arcgis.com/3.13/init.js:1086 Mixed Content: The page at 
'https://localhost/Viewer/' was loaded over HTTPS, but requested an 
insecure script 
'http://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/MODIS_Thermal/MapServer?f=json&callback=dojo.io.script.jsonp_dojoIoScript3._jsonpCallback'. 
This request has been blocked; the content must be served over HTTPS.
js.arcgis.com/3.13/init.js:1086 Mixed Content: The page at 
'https://localhost/Viewer/' was loaded over HTTPS, but requested an 
insecure script 
'http://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/Wildfire_Activit…apServer?f=json&callback=dojo.io.script.jsonp_dojoIoScript4._jsonpCallback'. 
This request has been blocked; the content must be served over HTTPS.


All of that is followed by more errors.  Apparently, the files it loads 
from tmservices1.esri.com are important.

**Comment by kellyhutchins** [comment]
The requests for tmservices1.esri.com are because the default web map specified in this application adds a layer from that server to the  map. Try creating a new web map in ArcGIS.com and replacing the web map id in config/defaults.js with the web map id for the map you create.

**Comment by tggagne** [comment]
Wow.  I don't know how you figured that out so quickly, but dang.

So here's my problem.  I don't necessarily need to get /this/ map working.  I need to get another map working that's hosted on ArcGIS Server--not Online.

So creating another map on ArcGIS won't, I think, help me get closer to my goal.  Correct me if I'm wrong.  What I would like to do next is configure Viewer to point to my client's REST endpoint and perhaps specify the URL of the basemap (on their own server).

Does that make sense?

**Comment by kellyhutchins** [comment]
@tggagne  you can create a web map definition that defines your contents (custom basemap etc) using the steps outlined in this wiki: https://github.com/Esri/Viewer/wiki/local-definition

**Comment by jgravois** [comment]
see also #16
