### ISSUE TITLE
Editor on mobile UI not working well

### ISSUE THREAD

**Issue by BlakeStearman** [Esri/Viewer#42]
Editing features on mobile with the viewer template UI needs to be changed to be more user friendly. It's not designed for small screens.

Either the template needs to handle this or the editing widget needs to use a more responsive design.

cc @driskull

**Comment by karmstro77** [comment]
Agreed. Here is a screenshot of editing experience on a Samsung Galaxy S6.

![image](https://cloud.githubusercontent.com/assets/6819070/14799797/71f6afac-0b0c-11e6-9921-c18c579b352c.png)

**Comment by Eh2406** [comment]
We are having the same problems. We are developing a map for data entry on mobile devices. We just noted that this "responsive" web map did not work well on mobile.

Is this going to be worked on soon?
Is there a different template that would work better for us?

**Comment by kellyhutchins** [comment]
Waiting for the api to build a responsive editing widget. Once there we'll add to app
