### ISSUE TITLE
Reordering Widgets

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/Viewer#49]
Is it possible to reorder the widgets in this template? If not, could you give me some guidance as to what would be required code wise to implement this?

**Comment by kellyhutchins** [comment]
@MKellyEsri  look for the line of code in main.js that adds the tools to the deferred array. Once all of the tools have been created we add them to the toolbar. The order they are added is the order of the tools in this list.  So if you change the order the toolbar position should change. 
 var toolDeferreds = [shareDef, tableDef, printDef, layerDef, basemapDef, bookmarksDef];

**Comment by MKellyEsri** [comment]
Thanks very much much for your reply Kelly, much appreciated. I'll look into this next week at some stage. Once I figure it out I'll post it up here in case anyone else wants to do the same thing.
