### ISSUE TITLE
New Behavior - Layers with tiers now show expanded on PC

### ISSUE THREAD

**Issue by mlrgisonline** [Esri/Viewer#51]
Before the latest update the "Layers" window would show only the highest tier data set. The update expanded all the layers to show all the data under the top tier. For example: I had an server based parcel layer in my project with all types of associated secondary layers. Before the update, the "Layers" window only displayed that top tier. Now I see the main layer with all the associated secondary layers expanded underneath and it has greatly diminished the ease of use as it makes the "Layers" window appear cluttered with data that the end user doesn't really need to view. See attached images Before and After the update. Unfortunately this expanded "Layers" window makes the Basic Viewer app unusable for my organization and I will be forced to consider migrating to another app.

![layers window expanded](https://cloud.githubusercontent.com/assets/10160990/8707781/208e334e-2af5-11e5-9343-6b24b7584543.jpg)
![layers window before update](https://cloud.githubusercontent.com/assets/10160990/8707783/2583f924-2af5-11e5-8cdc-92cc94235932.jpg)

**Comment by kellyhutchins** [comment]
@mlrgisonline  I'm sorry to hear that. Adding support for sub layers was one of the most common requests we received for this template.  
At the next release I can add a configuration option that allows you to disable sub layers for the hosted version. For this release if you download the template and host it locally you can modify the code to turn off sub layer support. To do so search the code for the LayerList widget then add the sublayers constructor option and set it to false.


                    var toc = new LayerList({
                        map: this.map,
                        subLayers: false,
                        layers: arcgisUtils.getLayerList(this.config.response)
                    }, domConstruct.create("div", {}, layersDiv));
                    toc.startup();

**Comment by mlrgisonline** [comment]
Hi Kelly,
Thanks for your quick response! Adding a configurable option to disable sub layers in the next release would be wonderful. I can see the benefit of being able to view sub layers however our layers are sometimes so complex that the Layers window becomes extremely cluttered. Expanding them has made the heads of non-GIS users in our organization collectively explode. :) Thanks for your help and I look forward to the next release!

**Comment by mlrgisonline** [comment]
Speaking to the complexity of sub layers. It was nice to build them, configure them (symbols, zoom levels, etc), and hide them under the primary in the Layers window. Giving the non-technical end user only one check-box to worry about was my version of employing the K.I.S.S doctrine.

Thanks again!

**Comment by kellyhutchins** [comment]
I agree simplicity is good!

**Comment by mlrgisonline** [comment]
Nearly all of our 15 employees complain about the expanded sub-layers on an almost daily basis. I keep telling them it's not that bad and a configuration setting is forthcoming in an updated release. I wish we had the resources to host locally but we rely on the served version.

**Comment by kellyhutchins** [comment]
@mlrgisonline its actually available now. It was updated in the minor update we did a few weeks ago. If you go to the config panel for the template you should see a new option about sub layers. Checking that will give you the 'old' behavior of the layer list. 
![screen shot 2015-09-16 at 11 09 29 am](https://cloud.githubusercontent.com/assets/2124187/9913794/7fffb2a4-5c63-11e5-9507-b0f534943b1d.png)

**Comment by jgravois** [comment]
@mlrgisonline i was gonna say, why not use something free like [github pages](https://help.github.com/articles/what-are-github-pages/)?.
kelly's response is much better.

**Comment by mlrgisonline** [comment]
Thanks for your replies. Checked for a configuration setting a little while ago so I must have just missed the update. 

John, thanks for the suggestion to host on Github. You'll be shocked to know that "web stuff" is not my area of expertise but with some reading and a little luck I'll machete' my way through it. :)

**Comment by jgravois** [comment]
i'm happy to help.  feel free to ping me using @jgravois in an issue like this (within your own repo) if you ever hit a roadblock.

closing this issue now, but feel free to post again if you've got more questions on the same topic.
