### ISSUE TITLE
Save button for Editing tool.

### ISSUE THREAD

**Issue by etes** [Esri/Viewer#53]
Many of our clients are used to saving edits manually after creating or modifying a feature. It would be more sensible if there is a "Save" button next to the delete button as it is difficult to determine whether the edits have been saved or not.

**Comment by kellyhutchins** [comment]
@etes  it is possible to add a save button to the editor. We have a sample in the JSAPI that shows how to do this if you want to customize the code and host the application on your web server. 

http://developers.arcgis.com/javascript/samples/ed_attribute_inspector/
