### ISSUE TITLE
Configure Layout

### ISSUE THREAD

**Issue by remmi11** [Esri/Viewer#55]
The read me mentions the map supports different layout options.  Can you point me in the direction of how this is configured? 

Thanks in advance...

**Comment by kellyhutchins** [comment]
The read-me is referring to print layout options. This is only for printing the app not the general app layout.  In order to use those you'll need a custom print service with layout options defined.

**Comment by remmi11** [comment]
Thank you Kelly.  Regarding configuring 'a custom print service with layout options defined'  is this  the right place to be looking for use with arcgis online.
<a href="https://doc.arcgis.com/en/arcgis-online/administer/configure-services.htm">Configure utility services</a> 
Or should I refer to something else...
Thanks again.

**Comment by jgravois** [comment]
@remmi11 ArcGIS Server is required to publish custom print services.  You can find some documentation on the topic [here](http://resources.arcgis.com/en/help/main/10.2/#/Using_your_own_layouts_for_printing/01540000057v000000/).
