### ISSUE TITLE
Portal installation help sought!  Not finding JavaScript libraries

### ISSUE THREAD

**Issue by ChrRobin** [Esri/Viewer#57]
My modified version of the app works perfectly with ArcGIS Online but not Portal for ArcGIS Server, apparently not finding libraries--this is a general question I have placed on ESRI's geonet SIG:

https://geonet.esri.com/message/547766#547766

![image](https://cloud.githubusercontent.com/assets/4522860/9610476/7c589e92-509f-11e5-90ae-7f2cf07bbdcd.png)

**Comment by jgravois** [comment]
closing, as issue was resolved in the geonet thread (thanks @bsvensson)
