### ISSUE TITLE
add cutvisible and reshapevisble to  editor  but can not   use them ,however  the union can workwell

### ISSUE THREAD

**Issue by giswt** [Esri/Viewer#58]

**Comment by kellyhutchins** [comment]
Can you reproduce this issue with one of the samples from the javascript help? 
https://developers.arcgis.com/javascript/jssamples/ags_editor.html

**Comment by giswt** [comment]
@kellyhutchins ,I try it.  I add the code to the sample as you say, it work well.
I made it work  outside the Framework(Viewer).  after  adding  the three tool(cut  reshape  union)
,I use the cut  tool ,it only query data  ,but the cut action does not be executed. 

![1](https://cloud.githubusercontent.com/assets/3362348/10409212/0d0ef4a0-6f49-11e5-8ee8-1277801e81f0.gif)
![2](https://cloud.githubusercontent.com/assets/3362348/10409213/136fc356-6f49-11e5-9a90-c84ceff0f620.png)

**Comment by giswt** [comment]
@kellyhutchins  I use  the webmap from the Arcgis  work well.
                        But when I  use data from my server ,it does no work.

**Comment by giswt** [comment]
@kellyhutchins , it can work now. But I have not found the  problem.
