### ISSUE TITLE
the link in resources is lost :Loading a locally-defined webmap, instead of from AGOL

### ISSUE THREAD

**Issue by gisfinder** [Esri/Viewer#64]
check the link please.

**Comment by jgravois** [comment]
thanks for pointing out the problem!  we moved that documentation into our [wiki](https://github.com/Esri/Viewer/wiki/local-definition) and forgot to update the link in the README.md.  the problem will be fixed as soon as pull request #65 is merged.

👍  to @kellyhutchins for writing such a pertinent and succinct commit message in b9e7e8374ce7e0e093d7ae5b3fe40b8b6d92ac3d.
