### ISSUE TITLE
search layer

### ISSUE THREAD

**Issue by michaelschnack** [Esri/Viewer#67]
Where can I edit the js to enable searching one or more layers from the search box (enable same functionality as editing search in the Configure Web App screen).

**Comment by kellyhutchins** [comment]
You can set the search values in the defaults.js file but the tricky part is getting the format correct. The simplest way to get the correct info is to configure the app using the Configure Web App screen then look at the saved json for the app to see the values it stores. For example I configured a test app to use one feature layer as a search laeyr and here is the output json.  If your configured app is public you can replace the id in the url below with the id of your configured app to see the values. 
http://www.arcgis.com/sharing/rest/content/items/8fb867c01b9c4886b1ff081a875802e4/data?f=json

**Comment by michaelschnack** [comment]
Thanks for the quick reply!
