### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by mrcdecoaticook** [Esri/Viewer#76]
Hi,

I noticed that even if there are NLS files for 34 languages, the language is not selected automatically based on the browser's locale.

**Comment by kellyhutchins** [comment]
The apps are available in 30+ locales and in my testing the browser locale is used to determine the app language. Note that text like the app title is dependent on the underlying configuration or web map and is not localized. But search strings, tooltips, widgets etc are.

**Comment by mrcdecoaticook** [comment]
Ok I tested a fresh copy of the app without making any changes and language selection works. I must had messed someting up when configuring and customizing the app. Sorry about that.
