### ISSUE TITLE
Remove Google Plus from Sharing panel

### ISSUE THREAD

**Issue by gavinr** [Esri/Viewer#77]
Since [Google+ is shutting down](https://www.blog.google/technology/safety-security/project-strobe/), we should remove that [sharing option](https://github.com/Esri/Viewer/blob/b50d09414e5b4f155d073602fa6d204db29dce78/js/ShareDialog.js#L332-L335).

**Comment by kellyhutchins** [comment]
Thanks I'll make an issue to remove it from the configurable apps.
